version: "2"
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3

    working_directory: /go/src/github/duyquang6/memes-fb-bot

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -v

      - run:
          name: Check code style
          command: go vet ./...