// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"todolist-facebook-chatbot/conf"
	"todolist-facebook-chatbot/repositories"
	"todolist-facebook-chatbot/services"
)

// Injectors from wire.go:

func injectTaskService() (*services.TaskService, error) {
	appConfig, err := conf.NewAppConfig()
	if err != nil {
		return nil, err
	}
	resource, err := repositories.NewResource(appConfig)
	if err != nil {
		return nil, err
	}
	taskRepository, err := repositories.NewTaskRepository(appConfig, resource)
	if err != nil {
		return nil, err
	}
	taskService, err := services.NewTaskService(taskRepository)
	if err != nil {
		return nil, err
	}
	return taskService, nil
}
